security:
  oauth2:
    client:
      clientId: 373032889736779
      clientSecret: 65a617a74542eb1328dbc363559ae9d4
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
